### PR TITLE
Set the title attribute for short links based on page title

### PR DESCRIPTION
**Pull request by zathras777**
Second attempt to add the setting of the title attribute for newly created or amended short links. This makes the display and management of the links easier. This pull uses the v2 API as v3 wasn't required.

### CODE REVIEW

**Comment by edward-shen** [comment]
Looks good. Can you squash changes into one commit and force push? This change should really just be in one commit.

**Comment by zathras777** [comment]
That pushes right against my limited git foo but will do some research 🙂

**Comment by zathras777** [comment]
Hopefully that looks better. Took me a couple of attempts to figure out what I was doing, but think the commit now looks better. Thanks for nudging me...

**Comment by edward-shen** [comment]
Yeah, looks great! Thanks for the contribution. I'll do a little bit of sanity checking before publishing an updated version.

**Pull request merged**
