### PR TITLE
Set the title of shortened links from the tab

### PR DESCRIPTION
**Pull request by zathras777**
Small change to set the title of the created short link based on the tab title. This makes managing the links easier and allows for better presentation. Version changed to 0.5.1 only to differentiate.

### CODE REVIEW

**Comment by edward-shen** [comment]
Hi! Thanks for your contribution! I think this needs to be bumped to the
next minor version, since it's a breaking change to use v3 of the API
endpoint.

**Comment by zathras777** [comment]
I wasn't 100% sure if the v3 interface was needed, but it was what my
server was using 🙂

I have a version that works locally so no hurry.

**Comment by edward-shen** [comment]
Actually, it looks like it's present in v2: https://api-spec.shlink.io/?version=v2.10.3#/Short%20URLs/createShortUrl

I think if you remove the V3 change it will be fine! V3 servers should support V2 API, judging by the API docs.

**Comment by zathras777** [comment]
Nice. I will withdraw the request and redo it.

**Pull request closed without merging**
